/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillInstagram, AiFillFacebook} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import code from '../public/code.png'
import design from '../public/design.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jayaswin Nadula</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
       
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">JNBT</h1>
            <ul className="flex items-center">
              <li className="text-gray-800 text-2xl dark:text-white">
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} />
              </li>
              <li>
                <a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 dark:bg-gradient-to-r dark:from-teal-500 dark:to-sky-600 dark:text-gray-800" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-5">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-sky-500">Jayaswin Nadula</h2>
            <h3 className="text-3xl py-2 md:text-3xl dark:text-white">Creative Designer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300">
              I'm a freelancer providing services for Design needs.<br/>
              Join me down below and let's get cracking! 
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-700 dark:text-sky-500">
            <a href="https://www.instagram.com/nadula.t/" target={"_blank"} rel={"noopener noreferrer"}><AiFillTwitterCircle/></a>
            <a href="https://www.instagram.com/nadula.t/" target={"_blank"} rel={"noopener noreferrer"}><AiFillInstagram/></a>
            <a href="https://www.instagram.com/nadula.t/" target={"_blank"} rel={"noopener noreferrer"}><AiFillFacebook/></a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full  w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 dark:bg-gradient-to-b dark:from-sky-300">
            <Image src={deved} alt ="3D avatar" layout="fill" objectFit="cover" />
          </div>
        </section>
        
        <section>
          <div className="text-center p-5">
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 mx-auto dark:text-gray-200">
            As a creative design freelancer I can provide a wide range of services. Here are some of the services that I offer: <br/>
            <span className="text-teal-600 dark:text-sky-500">Graphic Design</span>: This includes creating designs for logos, business cards, brochures, posters, social media posts, and others. <br/>
            <span className="text-teal-600 dark:text-sky-500">UI design</span>: This includes designing interfaces for websites, apps, and other digital platforms. <br/>
            <span className="text-teal-600 dark:text-sky-500">Illustration</span>: This includes creating original illustrations for use in various media. <br/>
            <span className="text-teal-600 dark:text-sky-500">Print design</span>: This involves designing materials for print, such as books, magazines, packaging, and other materials.  <br/>
            </p>
          </div>
          <div className="lg:flex gap-10">
          <a href="#logo">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 hover:bg-slate-100 dark:hover:bg-slate-800 ">
              <Image src={design} alt={design} width = {100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Logo Design</h3>
              <p className="py-2 dark:text-white">Creating <span className="text-teal-600 text-lg">elegant</span> logo designs suited for your business</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">Adobe Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Adobe Illustrator</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Canva</p>
            </div>
            </a>
            <a href="#ui">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 hover:bg-slate-100 dark:hover:bg-slate-800">
              <Image src={code} alt={design} width = {100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">UI Design</h3>
              <p className="py-2 dark:text-white">Creating <span className="text-teal-600 text-lg">simple, but stylish</span> UI designs suited for you</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">Figma</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Adobe XD</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">MockFlow</p>
            </div>
            </a>
            <a href="#illus">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 hover:bg-slate-100 dark:hover:bg-slate-800">
              <Image src={consulting} alt={design} width = {100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Illustration</h3>
              <p className="py-2 dark:text-white">Creating <span className="text-teal-600 text-lg">unique</span> illustrations suited for your need</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">Adobe Illustrator</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Adobe Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Krita</p>
            </div>
            </a>
            <a href="#print">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 hover:bg-slate-100 dark:hover:bg-slate-800">
              <Image src={consulting} alt={design} width = {100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Print Design</h3>
              <p className="py-2 dark:text-white">Creating <span className="text-teal-600 text-lg">eye-catching</span> print desings suited for your product</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-200">Adobe Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Adobe Illustrator</p>
              <p className="text-gray-800 py-1 dark:text-gray-200">Canva</p>
            </div>
            </a>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 p-5 dark:text-white text-center">My Portfolio</h3>
          </div>

            <h2 id="logo" className="text-2xl pt-5 py-1 p-5 text-teal-600 text-center">My Logo Desings</h2>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                <div className="basis-1/3 flex-1">
                  <Image src={web1} alt={web1} className="rounded-lg object-cover" width={100} height={100} layout="responsive"/>
                </div>
                <div className="basis-1/3 flex-1">
                  <Image src={web2} alt={web2} className="rounded-lg object-cover" width={100} height={100} layout="responsive"/>
                </div>
                <a href="#" className="text-center shadow-lg p-10 m-auto rounded-xl hover:bg-slate-100 text-teal-600 hover:text-teal-900 text-xl">See More</a>
            </div>
            
            <h2 id="ui" className="text-2xl pt-5 py-1 p-5 text-teal-600 text-center">My UI Desings</h2>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                <div className="basis-1/3 flex-1">
                  <Image src={web1} alt={web1} className="rounded-lg object-cover" width={100} height={100} layout="responsive"/>
                </div>
                <div className="basis-1/3 flex-1">
                  <Image src={web2} alt={web2} className="rounded-lg object-cover" width={100} height={100} layout="responsive"/>
                </div>
                <a href="#" className="text-center shadow-lg p-10 m-auto rounded-xl hover:bg-slate-100 text-teal-600 hover:text-teal-900 text-xl">See More</a>
            </div>

            <h2 id="illus" className="text-2xl pt-5 py-1 p-5 text-teal-600 text-center">My Illustrations</h2>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                <div className="basis-1/3 flex-1">
                  <Image src={web1} alt={web1} className="rounded-lg object-cover" width={100} height={100} layout="responsive"/>
                </div>
                <div className="basis-1/3 flex-1">
                  <Image src={web2} alt={web2} className="rounded-lg object-cover" width={100} height={100} layout="responsive"/>
                </div>
                <a href="#" className="text-center shadow-lg p-10 m-auto rounded-xl hover:bg-slate-100 text-teal-600 hover:text-teal-900 text-xl">See More</a>
            </div>

            <h2 id="print" className="text-2xl pt-5 py-1 p-5 text-teal-600 text-center">My Print Designs</h2>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                <div className="basis-1/3 flex-1">
                  <Image src={web1} alt={web1} className="rounded-lg object-cover" width={100} height={100} layout="responsive"/>
                </div>
                <div className="basis-1/3 flex-1">
                  <Image src={web2} alt={web2} className="rounded-lg object-cover" width={100} height={100} layout="responsive"/>
                </div>
                <a href="#" className="text-center shadow-lg p-10 m-auto rounded-xl hover:bg-slate-100 text-teal-600 hover:text-teal-900 text-xl">See More</a>
            </div>
            
        </section>

      </main>
    </div>
  );
}
